version: "3"

services:

  wsgi:
    container_name: core_wsgi
    build: .
    command: >
      sh -c "
            python3 manage.py runscript scripts.setup &&
            gunicorn -w 4 --bind 0.0.0.0:8000 core.wsgi:application --reload
            "
    env_file: .env
    volumes:
      - .:/app
    ports:
      - 8000:8000